"""
Django settings for knanalytics project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
LAUNCH_METHOD = 'POST'
LAUNCH_URL = 'https://pe-xl-prod.knowdl.com/econservice/econlaunch/toolLaunch/'
XLSIMS_LAUNCH_URL = 'https://pe-xl-prod.knowdl.com/xlsim/simLaunch/launch/'
#XLSIMS_LAUNCH_URL = 'https://dev.econdip.pearsoncmg.com/xlsim/simLaunch/launch/'
TPI_SHARED_SECRET = "ihvimlcr"
APP_REDIRECT_URL = "https://pe-xl-prod.knowdl.com/app"     # please to exclude trailing slash!!!
APP_REDIRECT_URL_CA = "https://pe-xl-prod.knowdl.com/ca/"
APP_REDIRECT_URL_UE = "https://pe-xl-prod.knowdl.com/unemployment/"
APP_REDIRECT_SETTINGS_URL_CA = "https://pe-xl-prod.knowdl.com/ca/settings.html"
APP_REDIRECT_SETTINGS_URL_UE = "https://pe-xl-prod.knowdl.com/unemployment/settings.html"
SIMS_EMULATOR_ROOT = '/content/atm_sims/simsEmulator/'
SIMS_ROOT = '/content/atm_sims/'

DATA_URI = ''
BYPASS_OAUTH = False
COURSE_REVIEW_LAUNCH_TABLE = {
    'unemployment': 'https://pe-xl-prod.knowdl.com/content/unemployment/classReview.html',
    'comparative_advantage': 'https://pe-xl-prod.knowdl.com/content/ca/classReview.html',
    'inflation': 'https://pe-xl-prod.knowdl.com/content/inflation/classReview.html',
    'opportunity_cost': 'https://pe-xl-prod.knowdl.com/content/oppcost/classReview.html',
    'monetary_policy': 'https://pe-xl-prod.knowdl.com/content/monetarypolicy/classReview.html',
    }

ECON_LAUNCH_TABLE = {
    'unemployment': 'https://pe-xl-prod.knowdl.com/content/unemployment/',
    'comparative_advantage': 'https://pe-xl-prod.knowdl.com/content/ca/',
    'inflation': 'https://pe-xl-prod.knowdl.com/content/inflation/',
    'opportunity_cost': 'https://pe-xl-prod.knowdl.com/content/oppcost/',
    'monetary_policy': 'https://pe-xl-prod.knowdl.com/content/monetarypolicy/',
    }

ECON_SETTINGS_LAUNCH_TABLE = {
    'unemployment': 'https://pe-xl-prod.knowdl.com/content/unemployment/settings.html',
    'comparative_advantage': 'https://pe-xl-prod.knowdl.com/content/ca/settings.html',
    'inflation': 'https://pe-xl-prod.knowdl.com/content/inflation/settings.html',
    'opportunity_cost': 'https://pe-xl-prod.knowdl.com/content/oppcost/settings.html',    
    'monetary_policy': 'https://pe-xl-prod.knowdl.com/content/monetarypolicy/settings.html',
    }

#OUTCOMES_URL = 'http://cert.isb.lift.pearsoncmg.com/v1/dataexchange/tpi/submit'
OUTCOMES_URL = 'https://isb.lift.pearsoncmg.com/v1/dataexchange/tpi/submit'
OUTCOMES_USER = 'appuser'
OUTCOMES_PW = 'appuser1'
DEBUG = True
TEMPLATE_DEBUG = DEBUG

ADMINS = (
    # ('Your Name', 'your_email@example.com'),
)

MANAGERS = ADMINS

ROOT_PATH = os.path.dirname(__file__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b)7q_ng8c)8t2_4c6e6k)g=+zad^!jowzc8a9=7m=*#w1s(b22'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STATIC_ROOT = os.path.join(ROOT_PATH, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

ALLOWED_HOSTS = ['*']

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
#     'django.template.loaders.eggs.Loader',
)

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gllaunch',
    'gldata',
    'datacapture',
    'econ.common_services',
    'econ.monetary_policy', 
    'econ.gdp', 
    'econ.ca',
    'econ.ue', 
    'econ.inflation',   
    'xlsims',
    'knowdlsim',
    'knowdlsim.templatetags',    
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'knanalytics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'knanalytics.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'econservice',
	'USER': 'root',
	'PASSWORD': 'Kn0wdl!23',
	'HOST': '172.16.1.33',
	'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'America/Chicago'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

FRED_API_KEY = '1c3266c33784d3a4a4b7875a34ae2364'
FRED_API_BASE_URL = 'https://api.stlouisfed.org/fred/series/observations?api_key=%s&file_type=json&observation_start=1960-01-01' % FRED_API_KEY


